{% set name = "gmso" %}
{% set version = "0.12.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mosdef-hub/gmso/archive/{{ version }}.tar.gz
  sha256: 773205a86473af5748270ded858c55eec9a210e73c2fd0331c78611e8554d468

build:
  noarch: python
  number: 1 
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9,<=3.12
    - setuptools
  run:
    - boltons
    - lxml
    - numpy
    - sympy
    - unyt >2.9.5
    - python >=3.9,<=3.12
    - pydantic >=2
    - foyer >=0.11.3
    - forcefield-utilities >=0.3.0
    - networkx
    - symengine
    - python-symengine
    - ele >=0.2.0
    - setuptools
    - importlib_resources
    - zstd

test:
  imports:
    - gmso

about:
  home: https://github.com/mosdef-hub/gmso
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Flexible storage of chemical topology for molecular simulation.

  description: |
    GMSO is designed to enable the flexible, general representation of chemical
    topologies for molecular simulation. Efforts are made to enable lossless,
    bias-free storage of data, without assuming particular chemistries, models,
    or using any particular engine's ecosystem as a starting point.
  doc_url: https://gmso.mosdef.org/
  dev_url: https://github.com/mosdef-hub/gmso

extra:
  recipe-maintainers:
    - bdice
    - justinGilmer
    - umesh-timalsina
    - daico007
    - rmatsum836
    - uppittu11
    - CalCraven
    - chrisjonesBSU
