{% set name = "gmso" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mosdef-hub/gmso/archive/{{ version }}.tar.gz
  sha256: 824607fc882b1a696a0c9c16bc5c7b433fc0f6aeeb4141d6a6958f50460f7c73

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - boltons
    - lxml
    - numpy
    - sympy
    - unyt <=2.8
    - python >=3.6
    - pydantic <1.9.0
    - networkx
    - ele >=0.2.0
    - setuptools

test:
  imports:
    - gmso

about:
  home: https://github.com/mosdef-hub/gmso
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Flexible storage of chemical topology for molecular simulation.

  description: |
    GMSO is designed to enable the flexible, general representation of chemical
    topologies for molecular simulation. Efforts are made to enable lossless,
    bias-free storage of data, without assuming particular chemistries, models,
    or using any particular engine's ecosystem as a starting point.
  doc_url: https://gmso.mosdef.org/
  dev_url: https://github.com/mosdef-hub/gmso

extra:
  recipe-maintainers:
    - bdice
    - justinGilmer
    - umesh-timalsina
    - daico007
    - rmatsum836
    - uppittu11
