{% set name = "gmso" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mosdef-hub/gmso/archive/{{ version }}.tar.gz
  sha256: 4774673590d01c66b45ba3a66b0679182503758b411e39c7e6184c62ae2c6742

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - boltons
    - lxml
    - numpy >=2.0,<2.3
    - sympy
    - unyt >2.9.5
    - python >={{ python_min }},<=3.13
    - pydantic >=2
    - foyer >=0.11.3
    - forcefield-utilities >=0.4.0
    - networkx
    - symengine
    - python-symengine
    - ele >=0.2.0
    - setuptools
    - importlib_resources
    - zstd

test:
  requires:
    - python {{ python_min }}
  imports:
    - gmso

about:
  home: https://github.com/mosdef-hub/gmso
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Flexible storage of chemical topology for molecular simulation.

  description: |
    GMSO is designed to enable the flexible, general representation of chemical
    topologies for molecular simulation. Efforts are made to enable lossless,
    bias-free storage of data, without assuming particular chemistries, models,
    or using any particular engine's ecosystem as a starting point.
  doc_url: https://gmso.mosdef.org/
  dev_url: https://github.com/mosdef-hub/gmso

extra:
  recipe-maintainers:
    - bdice
    - justinGilmer
    - umesh-timalsina
    - daico007
    - rmatsum836
    - uppittu11
    - CalCraven
    - chrisjonesBSU
